### ISSUE TITLE
It doesnt work

### ISSUE THREAD

**Issue by kyjarz** [InterPixelCoding/educake-answers#1]
**This just shows <=answer no matter what educake question. you have a nice design and nice idea but as someone who is used to modifying websites like this the only possible way to make a educake hack is either making a bot that spams through text and buttons and then stores in a database that then can be put back into the bot and then let the bot answer the questions fast. Or Just use chatgpt. Also if you would liek to get in contact with me so i can maybe help you with your idea please do. I have everything in my Bio**

**Comment by InterPixelCoding** [comment]
Hi there,
My friend has got a script of his own and is currently farming all of the answers and uploading them to a database. Once we have farmed all of the answer, I can add the actual functionality. My friend just wanted a website to be designed in the mean time. I'll let you know once farming is complete!

**Comment by kyjarz** [comment]
Oh Okay. I would love to see this answer Farming script is there a way i could get into Contact with your friend

**Comment by InterPixelCoding** [comment]
He's @smellyelephant on discord
